// src/react/DitheredBackground.tsx
import React from "react";
import { parseBackgroundArgs, renderBackgroundToCanvas } from "../core/engine";
import { renderBackgroundToCanvasWebGL } from "../core/webgl";
import type { BackgroundArgs } from "../core/types";

const DEFAULT_WIDTH = 1920;
const DEFAULT_HEIGHT = 1080;
export type DitheredBackgroundRenderer = "auto" | "canvas2d" | "webgl";

export interface DitheredBackgroundProps {
  args: BackgroundArgs | string;
  width?: number;
  height?: number;
  renderScale?: number;
  renderer?: DitheredBackgroundRenderer;
  zIndex?: number;
  className?: string;
  style?: React.CSSProperties;
  absolute?: boolean;
}

export const DitheredBackground: React.FC<DitheredBackgroundProps> = ({
  args,
  width = DEFAULT_WIDTH,
  height = DEFAULT_HEIGHT,
  renderScale,
  renderer = "auto",
  zIndex = 0,
  className,
  style,
  absolute = true,
}) => {
  const canvasRef = React.useRef<HTMLCanvasElement>(null);

  const argsKey = typeof args === "string" ? args : JSON.stringify(args);

  const parsedArgs = React.useMemo(() => {
    try {
      return parseBackgroundArgs(argsKey);
    } catch (error) {
      // Keep render path safe; invalid JSON should not crash the full composition.
      console.error("Failed to parse DitheredBackground args", error);
      return null;
    }
  }, [argsKey]);

  const dpr =
    renderScale ??
    (typeof window !== "undefined" ? window.devicePixelRatio || 1 : 1);
  const physicalWidth = Math.max(1, Math.round(width * dpr));
  const physicalHeight = Math.max(1, Math.round(height * dpr));

  React.useEffect(() => {
    if (!parsedArgs) {
      return;
    }

    const canvas = canvasRef.current;
    if (!canvas) {
      return;
    }

    const shouldTryWebGL = renderer === "auto" || renderer === "webgl";

    if (shouldTryWebGL) {
      const renderedViaWebGL = renderBackgroundToCanvasWebGL(
        canvas,
        width,
        height,
        parsedArgs,
      );
      if (renderedViaWebGL) {
        return;
      }
    }

    renderBackgroundToCanvas(canvas, width, height, parsedArgs);
  }, [parsedArgs, renderer, width, height, physicalWidth, physicalHeight]);

  return (
    <canvas
      ref={canvasRef}
      className={className}
      width={physicalWidth}
      height={physicalHeight}
      style={{
        ...(absolute ? { position: "absolute", top: 0, left: 0 } : null),
        width,
        height,
        pointerEvents: "none",
        zIndex,
        ...style,
      }}
    />
  );
};

// src/svelte/DitheredBackground.svelte
<script lang="ts">
  import { parseBackgroundArgs, renderBackgroundToCanvas } from "../core/engine";
  import { renderBackgroundToCanvasWebGL } from "../core/webgl";
  import type { BackgroundArgs } from "../core/types";

  type DitheredBackgroundRenderer = "auto" | "canvas2d" | "webgl";

  interface Props {
    args: BackgroundArgs | string;
    width?: number;
    height?: number;
    renderScale?: number;
    renderer?: DitheredBackgroundRenderer;
    zIndex?: number;
    class?: string;
    style?: string;
    absolute?: boolean;
  }

  let {
    args,
    width = 1920,
    height = 1080,
    renderScale,
    renderer = "auto",
    zIndex = 0,
    class: className,
    style,
    absolute = true,
  }: Props = $props();

  let canvas: HTMLCanvasElement;

  const dpr = $derived(
    renderScale ?? (typeof window !== "undefined" ? window.devicePixelRatio || 1 : 1)
  );
  const physicalWidth = $derived(Math.max(1, Math.round(width * dpr)));
  const physicalHeight = $derived(Math.max(1, Math.round(height * dpr)));

  const parsedArgs = $derived.by(() => {
    try {
      const key = typeof args === "string" ? args : JSON.stringify(args);
      return parseBackgroundArgs(key);
    } catch (error) {
      console.error("Failed to parse DitheredBackground args", error);
      return null;
    }
  });

  $effect(() => {
    if (!parsedArgs || !canvas) return;

    // Access reactive deps to trigger re-render
    void physicalWidth;
    void physicalHeight;

    const shouldTryWebGL = renderer === "auto" || renderer === "webgl";

    if (shouldTryWebGL) {
      const ok = renderBackgroundToCanvasWebGL(canvas, width, height, parsedArgs);
      if (ok) return;
    }

    renderBackgroundToCanvas(canvas, width, height, parsedArgs);
  });
</script>

<canvas
  bind:this={canvas}
  class={className}
  width={physicalWidth}
  height={physicalHeight}
  style:position={absolute ? "absolute" : undefined}
  style:top={absolute ? "0" : undefined}
  style:left={absolute ? "0" : undefined}
  style:width="{width}px"
  style:height="{height}px"
  style:pointer-events="none"
  style:z-index={zIndex}
  {style}
/>
